version: "3.9"

services:
  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    build:
      context: .
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    depends_on:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"

volumes:
  db_data:
